server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # React Router support
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend API
    location /api {
        proxy_pass http://server:5005;
    }

    # Uploaded images/files
    location /uploads {
        proxy_pass http://server:5005;
    }
}