apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cab-booking
  namespace: argocd

spec:
  project: cab-booking-project

  source:
    repoURL: https://github.com/vijaypatel7/cab-booking-system.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: cab-booking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true