apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cab-booking-monitoring
  namespace: argocd
  labels:
    app: cab-booking
    component: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: cab-booking-project

  source:
    repoURL: https://github.com/vijaypatel7/cab-booking-system.git
    targetRevision: main
    path: k8s/monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true