apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: cab-booking-project
  namespace: argocd

spec:
  description: Cab Booking Application

  sourceRepos:
    - https://github.com/vijaypatel7/cab-booking-system.git

  destinations:
    - namespace: cab-booking
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true