name: Cab Booking CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: client
        run: npm ci

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./client/Dockerfile
            load: true
            tags: cab-booking-client:latest


      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
            image-ref: cab-booking-client:latest
            format: table
            exit-code: 1
            ignore-unfixed: true
            severity: HIGH,CRITICAL

      - name: Tag FrontendImage
        run: |
            docker tag cab-booking-client:latest ${{ secrets.DOCKER_USERNAME }}/cab-booking-client:latest
            docker tag cab-booking-client:latest ${{ secrets.DOCKER_USERNAME }}/cab-booking-client:${{ github.sha }}    

      - name: Push Images
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/cab-booking-client:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/cab-booking-client:${{ github.sha }}


      - name: Install Backend Dependencies
        working-directory: server
        run: npm ci


      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
            context: ./server
            load: true
            tags: cab-booking-server:latest

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
            image-ref: cab-booking-server:latest
            format: table
            exit-code: 1
            ignore-unfixed: true
            severity: HIGH,CRITICAL

      - name: Tag Backend Image
        run: |
            docker tag cab-booking-server:latest ${{ secrets.DOCKER_USERNAME }}/cab-booking-server:latest
            docker tag cab-booking-server:latest ${{ secrets.DOCKER_USERNAME }}/cab-booking-server:${{ github.sha }}
        
      - name: Push Backend Images
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/cab-booking-server:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/cab-booking-server:${{ github.sha }}

